language: objective-c
osx_image: xcode8
script:
- xcodebuild -project SwiftUtilities.xcodeproj -scheme SwiftUtilities_iOS -sdk iphonesimulator build
- xcodebuild -project SwiftUtilities.xcodeproj -scheme SwiftUtilities_OSX build test

