language: objective-c
osx_image: xcode7
script:
   - xctool -project SwiftUtilities.xcodeproj -scheme SwiftUtilities_OSX build test
   - xctool -project SwiftUtilities.xcodeproj -scheme SwiftUtilities_iOS -sdk iphonesimulator build test
