language: objective-c

osx_image: xcode7.2

env:
  global:
  - FRAMEWORK_NAME=SwiftUtilities

before_install:
- brew update
- brew install carthage
#before_script:
#- carthage bootstrap

script:
- xctool -project SwiftUtilities.xcodeproj -scheme "SwiftUtilities_OSX" -sdk macosx build test
- xctool -project SwiftUtilities.xcodeproj -scheme "SwiftUtilities_iOS" -sdk iphonesimulator build

before_deploy:
- carthage build --no-skip-current
- carthage archive $FRAMEWORK_NAME
